name: release

on:
  push:
    branches: [master]

permissions: write-all

jobs:
  buf-push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master

      - name: Make
        run: make

      - name: Push
        run: make buf-push
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
